#!/usr/bin/perl
use strict;
use utf8;
use Tweet;
use feature qw( say );

my $twitter = Tweet->new();
$twitter->init( { 'pit_twitter' => 'twitter.ForeignNewsFeeds',
									'pit_bitly'		=> 'bit.ly',
								}
							);

my $message = 'やばいっしょ';
my $url = '';
$twitter->post_tweet($message, $url);
if ($twitter->is_success){
	say 'post_succeeded';
}else{
	say $twitter->is_error;
}


